### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by fishilico** [mubix/IOXIDResolver#2]
Hello,

The [README.md](https://github.com/mubix/IOXIDResolver/blob/master/README.md) refers to interesting blog articles:

> - The source from this blog post: https://airbus-cyber-security.com/the-oxid-resolver-part-1-remote-enumeration-of-network-interfaces-without-any-authentication/
> - Part 2 of that blog post: https://airbus-cyber-security.com/the-oxid-resolver-part-2-accessing-a-remote-object-inside-dcom/

But these links now redirect to https://www.cyber.airbus.com/ directly. The articles are available at https://www.protect.airbus.com/blog/the-oxid-resolver-part-1-remote-enumeration-of-network-interfaces-without-any-authentication/ and https://www.protect.airbus.com/blog/the-oxid-resolver-part-2-accessing-a-remote-object-inside-dcom/ , but the images do not work, because they still refer to https://airbus-cyber-security.com/wp-content/uploads/2020/04/...

To prevent such issues, it would be nice to host this blog on a more long-term website, or to update `README.md` with links to some archives (for example https://web.archive.org/web/20220625011947/https://airbus-cyber-security.com/the-oxid-resolver-part-1-remote-enumeration-of-network-interfaces-without-any-authentication/ and https://web.archive.org/web/20220417063110/https://airbus-cyber-security.com/the-oxid-resolver-part-2-accessing-a-remote-object-inside-dcom/ ). What do you think?

**Comment by cookpoo78** [comment]
```+ 1 ^```

**Comment by mubix** [comment]
Thanks, just saw this issue due to a pull request. I'll get them updated.

**Comment by mubix** [comment]
Looks like they changed again:
- https://www.cyber.airbus.com/the-oxid-resolver-part-1-remote-enumeration-of-network-interfaces-without-any-authentication/
- https://www.cyber.airbus.com/the-oxid-resolver-part-2-accessing-a-remote-object-inside-dcom/
